Repository SANDQVISTT/-FE21-JS2-slutprojekt-GritVerse, pull requests merged in 2022-03, with the labels that each got.

#12 Added databaseURL
  .gitignore
  src/html/home.html
  src/index.html
  src/main.ts
  src/modules/display.ts
  src/modules/firebaseApp.ts
Labels: bug

#16 [Add] chat init-j
  src/html/forum.html
  src/html/home.html
  src/html/profile.html
  src/index.html
  src/main.ts
  src/modules/messages.ts
Labels: DB, TS, HTML

#17 [BUG] forgot to add recent changes - chat init j
  package.json
  src/css/style.css
  src/html/forum.html
  src/index.html
  src/main.ts
  src/modules/display.ts
  src/modules/firebaseApp.ts
  src/modules/messages.ts
Labels: bug, TS

#21 [BUG]Changed scripts to load on each site
  src/css/style.css
  src/html/forum.html
  src/html/profile.html
  src/main.ts
  src/modules/firebaseApp.ts
  src/modules/messages.ts
  src/modules/profile.ts
Labels: TS

#23 [ADD] css styling-j
  src/css/loginStyle.css
  src/css/style.css
  src/index.html
Labels: CSS

#24 [ADD] Login and Register now works!
  src/css/style.css
  src/gender.json
  src/index.html
  src/main.ts
  src/modules/display.ts
  src/modules/firebaseApp.ts
Labels: DB, TS

#26 [ADD] homepage functions
  src/css/home.css
  src/css/profile.css
  src/css/style.css
  src/html/home.html
  src/html/profile.html
  src/modules/home.ts
Labels: DB, TS

#28 [FIX] Showing the profile info on the profile site.
  src/html/profile.html
  src/main.ts
  src/modules/firebaseApp.ts
  src/modules/profile.ts
Labels: DB, TS

#27 [ADD] fixed css for forums
  src/css/forumSecondaryStyle.css
  src/css/style.css
  src/html/forum/forumGames.html
  src/html/forum/forumMusic.html
  src/html/forum/forumShows.html
  src/html/forumMain.html
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
Labels: CSS

#30 [BUG] Fixed database url duplicate
  src/modules/firebaseApp.ts
Labels: bug

#33 [FIX] Fixed timestamp and logout pages
  src/html/home.html
  src/html/profile.html
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
Labels: bug, TS

#39 [FIX] CSS on profile Page
  src/css/profile.css
  src/html/profile.html
  src/modules/home.ts
Labels: CSS

#42 [BUG] Login page works again
  src/index.html
Labels: bug

#44 [UPDATE] README.md
  README.md
Labels: documentation
