Repository SANDQVISTT/-FE21-JS2-slutprojekt-GritVerse, pull requests merged in 2022-04, with the labels that each got.

#45 [UPDATE] Final touch on login/signup
  src/gender.json
  src/modules/display.ts
  src/modules/firebaseApp.ts
Labels: enhancement

#46 [ADD] username now works in forums
  src/html/forum/forumGames.html
  src/html/forum/forumMusic.html
  src/html/forum/forumShows.html
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
Labels: TS

#47 [FIX] Update on the home-page. CSS & TS
  src/css/home.css
  src/html/home.html
  src/modules/home.ts
Labels: CSS, TS

#50 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#49 Create LICENSE
  LICENSE
Labels: documentation

#48 [ADD] clear sessionstorage on pages with the actual nav-button
  src/main.ts
  src/modules/firebaseApp.ts
  src/modules/home.ts
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
  src/modules/profile.ts
Labels: TS

#51 [BUG] Removed curly brackets that was giving an error
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
Labels: bug

#52 [BUG] fixed issue where sessionstorage was re-initialized upon logout
  src/modules/home.ts
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
  src/modules/profile.ts
Labels: bug, TS

#53 added code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#54 [BUG] added script to forumMain
  src/html/forumMain.html
  src/modules/logout.ts
Labels: bug, TS

#56 [FIX] Login/Signup page now works fully
  src/main.ts
  src/modules/firebaseApp.ts
Labels: bug, TS

#57 Create a CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#58 Created pull request template
  docs/pull_request_template.md
Labels: documentation

#61 [FIX] Fixed responsive on index.html and more
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  docs/pull_request_template.md
  src/css/forumSecondaryStyle.css
  src/css/home.css
  src/css/loginStyle.css
  src/css/profile.css
  src/css/responsive.css
  src/css/style.css
  src/index.html
  src/main.ts
  src/modules/display.ts
  src/modules/firebaseApp.ts
Labels: enhancement, CSS, TS

#62 [ADD] description added automatically
  package.json
Labels: documentation

#63 [BUG] removeBtn only shows up on your own messages
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
Labels: bug, TS

#64 [ADD] Funktion för att välja profilbild när man reggar användare.
  src/html/profile.html
  src/index.html
  src/modules/display.ts
  src/modules/firebaseApp.ts
  src/modules/profile.ts
Labels: DB, TS, HTML

#65 [BUG] Session storage fix and more
  src/css/forumSecondaryStyle.css
  src/css/loginStyle.css
  src/html/forum/forumGames.html
  src/html/forum/forumMusic.html
  src/html/forum/forumShows.html
  src/index.html
  src/modules/display.ts
  src/modules/firebaseApp.ts
  src/modules/home.ts
  src/modules/logout.ts
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
  src/modules/profile.ts
Labels: bug, CSS, TS

#66 [FIX] Select profilePictures
  src/html/profile.html
  src/index.html
  src/main.ts
  src/modules/firebaseApp.ts
  src/modules/logout.ts
  src/modules/profile.ts
Labels: HTML

#67 [ADD] Delete profile
  src/modules/deleteUser.ts
  src/modules/firebaseApp.ts
  src/modules/profile.ts
Labels: DB, TS

#69 [FIX] Delete only your own profile
  src/html/profile.html
  src/modules/deleteUser.ts
  src/modules/firebaseApp.ts
  src/modules/home.ts
  src/modules/messagesShows.ts
  src/modules/profile.ts
Labels: bug, TS

#70 [ADD]added comments and removed usused code
  src/modules/messagesGames.ts
  src/modules/messagesMusic.ts
  src/modules/messagesShows.ts
Labels: documentation, TS

#75 [FIX] Changed file directories so pages work.
  docs/html/forum/forumGames.html
  docs/html/forum/forumMusic.html
  docs/html/forum/forumShows.html
  docs/html/forumMain.html
  docs/html/home.html
  docs/html/profile.6aa6ca92.js
  docs/html/profile.html
Labels: bug

#76 [BUG] maestros' instructions
  docs/forumMusic.html
  docs/forumShows.html
  docs/home.html
  docs/index.6b2275d1.js
  docs/index.6b2275d1.js.map
  docs/index.html
  docs/profile.html
Labels: bug, documentation, TS
